symfonycasts_reset_password:
    lifetime: 3600           # Durée de validité des tokens (en secondes)
    throttle_limit: 3600     # Délai minimum entre deux requêtes pour un nouveau token
    request_password_repository: App\Repository\ResetPasswordRequestRepository
